on:
  push:
    branches:
      - main
      - master

name: website

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: release

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Debug
        run: |
          mkdir ./_book
          echo "This is a file" > ./_book/test.md
          cat ./_book/test.md

      - name: Prepate deployment
        uses: actions/checkout@v2
        with:
          path: book-output
          ref: gh-pages

      - name: Deploy site
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./_deploy.sh
          ./_deploy.sh

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install system dependencies
        run: |
          sudo apt-get -y install libcurl4-openssl-dev coinor-libsymphony-dev coinor-libcbc-dev coinor-libclp-dev ghostscript texlive-extra-utils
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_bioc("lpsymphony")
          tinytex::install_tinytex()
        shell: Rscript {0}

      - name: Build site
        run: |
          chmod +x ./_build.sh
          ./_build.sh

      - name: Deploy site
        run: |
          chmod +x ./_deploy.sh
          ./_deploy.sh
